<?php

namespace AppBundle\Repository;

/**
 * OperacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use AppBundle\Entity\Operacion;
use Doctrine\ORM\Query;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

class OperacionRepository extends \Doctrine\ORM\EntityRepository
{
    const NUMPAG=20;
    /**
     * @return Query
     */
    public function queryLatest()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM AppBundle:Operacion p
                JOIN p.reserva r
                WHERE r.fecha_inicio <= :now
                ORDER BY r.fecha_inicio DESC
            ')
            ->setParameter('now', new \DateTime());
    }

    public function operacionEntre($fechadesde, $fechahasta)
    {
//        $resultado = array();
//
//        $em = $this->getEntityManager();
//        $operacions = $em->getRepository('AppBundle:Operacion')->findAll();
//        $inicio = new \DateTime($fechadesde);
//        $fin = new \DateTime($fechahasta);
//        foreach ($operacions as $ope) {
//            if (($ope->getReserva()->getFechaInicio() > $inicio) and
//                ($ope->getReserva()->getFechaFin() < $fin)){
//                array_push($resultado, $ope);
//            }
//        }
//        return $resultado;

        return $this->getEntityManager()
            ->createQuery( "
          SELECT o
          FROM AppBundle:Operacion o
          JOIN o.reserva r 
          where r.fecha_inicio BETWEEN :fechaDesde and :fechaHasta
          ORDER BY r.fecha_inicio DESC
          ")
            ->setParameter('fechaDesde', new \DateTime($fechadesde))
            ->setParameter('fechaHasta', new \DateTime($fechahasta))
            ;
    }

    /**
     * @param int $page
     * @return Pagerfanta
     */
    public function findLatest($page = 1, $datos)
    {
        if($datos !== null)
        {
            $paginator = new Pagerfanta(new DoctrineORMAdapter($this->operacionEntre($datos["fechaIni"], $datos["fechaFin"]), false));
        }else{
            $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryLatest(), false));
        }
        $paginator->setMaxPerPage(self::NUMPAG);// llama a global en personal para cantidad de paginas Personal::NUM_ITEMS
        $paginator->setCurrentPage($page);

        return $paginator;
    }
}
